config/routes.rb
Rails.application.routes.draw do

  resources :unique_crates

  resources :items
  resources :categories
  resources :crates

  devise_for :users
  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :crates
end

app/models/crate.rb
class Crate < ActiveRecord::Base
  belongs_to :category
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :crate
  has_and_belongs_to_many :unique_crates

  mount_uploader :image, ProductImageUploader
end

app/models/unique_crate.rb
class UniqueCrate < ActiveRecord::Base
  belongs_to :user
  belongs_to :crate
  has_and_belongs_to_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :unique_crates

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :authenticate_user!, :except => [:index, :show, :update]
  before_action :get_last_crate

  protect_from_forgery with: :exception

  def get_last_crate
    if user_signed_in? and current_user.unique_crates.count > 0
      @last_crate = current_user.unique_crates.last.id
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    @crates = @category.crates
    render 'show', :locals => { crates: @crates }
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/crates_controller.rb
class CratesController < ApplicationController
  before_action :set_crate, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def checkout
    @items = @crate.items
    respond_with(@crate)
  end

  def index
    @crates = Crate.all
    respond_with(@crates)
  end

  def show
    @items = @crate.items
    @unique_crate = UniqueCrate.new
    respond_with(@crate)
  end

  def new
    @crate = Crate.new
    respond_with(@crate)
  end

  def edit
  end

  def create
    @crate = Crate.new(crate_params)
    @crate.save
    respond_with(@crate)
  end

  def update
    @crate.update(crate_params)
    respond_with(@crate)
  end

  def destroy
    @crate.destroy
    respond_with(@crate)
  end

  private
    def set_crate
      @crate = Crate.find(params[:id])
    end

    def crate_params
      params.require(:crate).permit(:crate, :name, :description)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    @crates = Crate.all

    render 'new', :locals => {item: @item, crates: @crates }
  end

  def edit
    @crates = Crate.all
  end

  def create
    @item       = Item.new(item_params)
    # @fer: TODO FIXMEUP
    @item.image = File.open(params[:item][:image][0].tempfile)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    @item.save
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.fetch(:image, {})
      params.require(:item).permit(:item, :name, :description, :price, :image, :crate_id)
    end
end

app/controllers/unique_crates_controller.rb
class UniqueCratesController < ApplicationController
  before_action :set_unique_crate, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @unique_crates = UniqueCrate.all
    respond_with(@unique_crates)
  end

  def show
    @total_price = 0
    @unique_crate.items.each do |item|
      @total_price += item.price
    end
    respond_with(@unique_crate)
  end

  def new
    @unique_crate = UniqueCrate.new
    respond_with(@unique_crate)
  end

  def edit
  end

  def create
    @unique_crate = UniqueCrate.new(unique_crate_params)
    @unique_crate.user_id = current_user.id
    @unique_crate.save
    respond_with(@unique_crate)
  end

  def update
    @unique_crate.update(unique_crate_params)
    respond_with(@unique_crate)
  end

  def destroy
    @unique_crate.destroy
    respond_with(@unique_crate)
  end

  private
    def set_unique_crate
      @unique_crate = UniqueCrate.find(params[:id])
    end

    def unique_crate_params
      params.require(:unique_crate).permit(:crate_id, :item_ids => [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def checkout
    @unique_crate = Crate.all.sample
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/crates_helper.rb
module CratesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/unique_crates_helper.rb
module UniqueCratesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="categories-index-container" style="display: none;">

  <ol class="breadcrumb">
    <li><a href="/">Categories</a></li>
  </ol>

  <div class="container flexslider" id="cat-container">
  <% @categories.each do |category| %>
    <div class="box">
      <a href="/categories/<%= category.id %>"><%= category.name %></a>
      <div class="box-image">
        <a href="/categories/<%= category.id %>"><%= image_tag(category.image) %></a>
      </div>
    </div>
  <% end %>
  </div>

</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<ol class="breadcrumb">
  <li><a href="/">Categories</a></li>
  <li><a href="/categories/<%= @category.id %>"><%= @category.name %></a></li>
</ol>

<p id="notice"><%= notice %></p>

<div class="container">
  <% @crates.each do |crate| %>
    <div class="crate-list"><a href="/crates/<%= crate.id%>"><%= crate.name %></p>
    <p id="crate-temp"><%= image_tag(crate.image) %></p></a></div>
  <% end %>
</div>

app/views/crates/_form.html.erb
<%= form_for(@crate) do |f| %>
  <% if @crate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crate.errors.count, "error") %> prohibited this crate from being saved:</h2>

      <ul>
      <% @crate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crates/edit.html.erb
<h1>Editing crate</h1>

<%= render 'form' %>

<%= link_to 'Show', @crate %> |
<%= link_to 'Back', crates_path %>

app/views/crates/index.html.erb
<h1>Listing crates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category Id</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crates.each do |crate| %>
      <tr>
        <td><%= crate.name %></td>
        <td><%= crate.category_id %></td>
        <td><%= crate.description %></td>
        <td><%= link_to 'Show', crate %></td>
        <td><%= link_to 'Edit', edit_crate_path(crate) %></td>
        <td><%= link_to 'Destroy', crate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crate', new_crate_path %>

app/views/crates/new.html.erb
<h1>New crate</h1>

<%= render 'form' %>

<%= link_to 'Back', crates_path %>

app/views/crates/show.html.erb
<ol class="breadcrumb">
  <li><a href="/">Categories</a></li>

  <li><a href="/categories/<%= @crate.category_id %>"><%= @crate.category.name %></a></li>
  <li><a href="/crates/<%= @crate.id %>"><%= @crate.name %></a></li>
</ol>

<div class="app-container" data-crateid="<%= @crate.id %>" ng-app="checkboxApp" ng-controller="checkboxCtl">

<p id="notice"><%= notice %></p>


  <div class="row">




    <div class="col-md-4 left-thumbnails">
      <h1><%= @crate.name %></h1>
        <%= form_for(@unique_crate) do |f| %>
          <input type="hidden" name="unique_crate[item_ids][]" value="{{ item.id }}" ng-repeat="item in items | filter:{checked: true}">
          <input type="hidden" name="unique_crate[crate_id]" value="<%= @crate.id %>">
          <%= f.submit "BUY CRATE", class: "btn btn-large btn-danger"%>
        <% end %>
      <br>



      <div class="crate-background">
        <div ng-repeat="item in items | filter:{checked:true}">
            <img id="left-thumbnail-img" src="{{item.image.url}}" style="transform:rotate({{item.rotation}}deg)">
        </div>
      </div>
    </div>
        <h3>Total Price $ {{ totalPrice() }}</h3>


    <div class="col-md-8" id="scroll-content">
      <div>
        <div class="row well well-sm" ng-repeat="item in items" id="item-contents">
          <label class="checkboxtext">
            <div class="col-md-1">
              <input type="checkbox" class="checkbox" ng-model="item.checked" />
            </div>
            <div class="col-md-3">
              <div class="thumbnail-image">
                <img src="{{item.image.url}}">
              </div>

            </div>
            <div class="col-md-8">
              <div class="caption">
                <h3>{{item.name}}</h3>
                <p>{{item.description}}</p>
                <p>$ {{item.price}}</p>

              </div>
            </div>
          </label>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :crate %><br>
    <%= f.select(:crate_id, options_from_collection_for_select(@crates, 'id', 'name') ) %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Crate ID</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= item.crate_id %></td>
        <td><%= image_tag(item.image) %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="item-list">
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Crate :</strong>
  <%= @item.crate.name %>
</p>

<p id="crate-temp">
  <strong>Image:</strong>
  <%= image_tag(@item.image) %>
</p>
</div>

<p>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crate Drop | Not for Everyone</title>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

</head>

<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->

      <a href="/" class="navbar-brand"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span></a>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">


          <li id="login">
            <% if user_signed_in? %>
              <strong><%= current_user.email %></strong>
              <button class="btn btn-default">
                <%= link_to(raw("<span class='glyphicon glyphicon-user' aria-hidden='true'></span>"), edit_user_registration_path, :class => 'navbar-link' )%>
              </button>
              <button class="btn btn-default">
                <%= link_to(raw("<span class='glyphicon glyphicon-eject' aria-hidden='true'></span>"), destroy_user_session_path, method: :delete, :class => 'navbar-link')  %>
              </button>
              <button class="btn btn-default">
                <% if @last_crate %>
                  <a href="/unique_crates/<%= @last_crate %>"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a>
                <% end %>
              </button>

            <% else %>
              <button class="btn btn-default">
                <%= link_to(raw("<span class='glyphicon glyphicon-user' aria-hidden='true'></span>"),new_user_registration_path, :class => 'navbar-link') %>
              </button>
              <button class="btn btn-default">
                <%= link_to(raw("<span class='glyphicon glyphicon-play' aria-hidden='true'></span>"), new_user_session_path, :class => 'navbar-link')  %>
              </button>
            <% end %>


            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

  </nav>



  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<div class="title">
  <p class="header">CRATE DROP</p>
  <p class="under-header">GIFT BUYING MADE EASY</p>
</div>

<div class="contents">
  <%= yield %>
</div>


  <!-- Remember: javascript tag before adding jquery scripts -->
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js' %>


</body>
</html>

app/views/unique_crates/_form.html.erb
<%= form_for(@unique_crate) do |f| %>
  <% if @unique_crate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unique_crate.errors.count, "error") %> prohibited this unique_crate from being saved:</h2>

      <ul>
      <% @unique_crate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :crate_id %><br>
    <%= f.text_field :crate_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unique_crates/edit.html.erb
<h1>Editing unique_crate</h1>

<%= render 'form' %>

<%= link_to 'Show', @unique_crate %> |
<%= link_to 'Back', unique_crates_path %>

app/views/unique_crates/index.html.erb
<h1>Listing unique_crates</h1>

<table>
  <thead>
    <tr>
      <th>Crate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unique_crates.each do |unique_crate| %>
      <tr>
        <td><%= unique_crate.crate %></td>
        <td><%= link_to 'Show', unique_crate %></td>
        <td><%= link_to 'Edit', edit_unique_crate_path(unique_crate) %></td>
        <td><%= link_to 'Destroy', unique_crate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unique crate', new_unique_crate_path %>

app/views/unique_crates/new.html.erb
<h1>New unique_crate</h1>

<%= render 'form' %>

<%= link_to 'Back', unique_crates_path %>

app/views/unique_crates/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <div class="container">
        <div class="row">
          <div class="col-xs-8">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="panel-title">
                  <div class="row">
                    <div class="col-xs-6" id="cart-header">
                      <h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
                    </div>
                    <div class="col-xs-6">
                      <button type="button" class="btn btn-primary btn-sm btn-block">
                        <span class="glyphicon glyphicon-share-alt"></span><a href="/"> Continue shopping</a>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-body">

                <% @unique_crate.items.each do |item| %>

                <div class="row">
                  <div class="col-xs-2"><img class="img-responsive" src=<%= item.image.url %>>
                  </div>
                  <div class="col-xs-4">
                    <h4 class="product-name"><strong><%= item.name %></strong></h4><h4><small></small></h4>
                  </div>
                  <div class="col-xs-6">
                    <div class="col-xs-6 text-right">
                      <h6>
                        <strong><%= number_to_currency item.price, precision: 0 %>
                        <span class="text-muted"></span></strong>
                      </h6>
                    </div>
                    <div class="col-xs-4">

                    </div>
                    <div class="col-xs-2">
                      <button type="button" class="btn btn-link btn-xs">
                        <span class="glyphicon glyphicon-trash"> </span>
                      </button>
                    </div>
                  </div>
                </div>
                <hr>

                <% end %>

                <div class="row">
                  <div class="text-center">
                    <div class="col-xs-9">
                    </div>
                    <div class="col-xs-3">
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-footer">
                <div class="row text-center">
                  <div class="col-xs-9">
                    <h4 class="text-right">Total $ <strong><%= @total_price %></strong></h4>
                  </div>
                  <div class="col-xs-3">


                  <!-- Large modal -->
                    <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target=".bs-example-modal-lg">Checkout</button>

                    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                          <h1>Thanks for shopping! Your crate's on the way!</h1>
                          <img src="https://s3.amazonaws.com/uploads.hipchat.com/39979/1220036/vMy9rNVMrj7Ltxf/cratedrop.jpg" alt="end image" id="end-image">
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="container">
          <div class="row">
              <div class="col-xs-12 col-md-4">
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h3 class="panel-title">
                              Payment Details
                          </h3>
                          <div class="checkbox pull-right">
                              <label>
                                  <input type="checkbox" />
                                  Remember
                              </label>
                          </div>
                      </div>
                      <div class="panel-body">
                          <form role="form">
                          <div class="form-group">
                              <label for="cardNumber">
                                  CARD NUMBER</label>
                              <div class="input-group">
                                  <input type="text" class="form-control" id="cardNumber" placeholder="Valid Card Number"
                                      required autofocus />
                                  <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-xs-7 col-md-7">
                                  <div class="form-group">
                                      <label for="expityMonth">
                                          EXPIRY DATE</label>
                                      <div class="col-xs-6 col-lg-6 pl-ziro">
                                          <input type="text" class="form-control" id="expityMonth" placeholder="MM" required />
                                      </div>
                                      <div class="col-xs-6 col-lg-6 pl-ziro">
                                          <input type="text" class="form-control" id="expityYear" placeholder="YY" required /></div>
                                  </div>
                              </div>
                              <div class="col-xs-5 col-md-5 pull-right">
                                  <div class="form-group">
                                      <label for="cvCode">
                                          CV CODE</label>
                                      <input type="password" class="form-control" id="cvCode" placeholder="CV" required />
                                  </div>
                              </div>
                          </div>
                          </form>
                      </div>
                  </div>
                  <ul class="nav nav-pills nav-stacked">
                      <li class="active"><a href="#"><span class="badge pull-right"><span class="glyphicon glyphicon-usd"></span>4200</span> Final Payment</a>
                      </li>
                  </ul>
                  <br/>
                  <a href="http://www.jquery2dotnet.com" class="btn btn-success btn-lg btn-block" role="button">Pay</a>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<button class="btn btn-default"><a href="/categories">Let's look at those crates</a></button>